import AddImage from "./Add.svg";
import AvatarBlueImage from "./AvatarBlue.svg";
import AvatarGreenImage from "./AvatarGreen.svg";
import AvatarPinkImage from "./AvatarPink.svg";
import AvatarPurpleImage from "./AvatarPurple.svg";
import AvatarRedImage from "./AvatarRed.svg";
import AvatarTealImage from "./AvatarTeal.svg";
import CheckboxSelectedImage from "./Checkbox-selected.svg";
import CheckboxUnselectedImage from "./Checkbox-unselected.svg";
import ChevronDownIcon from "./Chevron-down.svg";
import ChevronDownDisabledIcon from "./ChevronDownDisabled.svg";
import ChevronLeftIcon from "./Chevron-left.svg";
import ChevronLeftDisabledIcon from "./ChevronLeftDisabled.svg";
import ChevronRightIcon from "./Chevron-right.svg";
import ChevronRightDisabledIcon from "./ChevronRightDisabled.svg";
import ChevronUpIcon from "./Chevron-up.svg";
import ChevronUpDisabledIcon from "./ChevronUpDisabled.svg";
import ClearSearchBarIcon from "./Clear-searchbar.svg";
import Dismiss from "./Dismiss.svg";
import EmptyIllustration from "./EmptyIllustration.svg";
import ErrorIllustration from "./ErrorIllustration.svg";
import ErrorSmallIllustration from "./ErrorSmall-illustration.svg";
import EmptySmallIllustration from "./EmptySmallIllustration.svg";
import Error from "./Error.svg";
import Expired from "./Expired.svg";
import FileIcon from "./FileIcon.svg";
import Image from "./Image.svg";
import Important from "./Important.svg";
import InfoFilled from "./Info-filled.svg";
import InfoOutline from "./Info-outline.svg";
import InReview from "./InReview.svg";
import Laptop from "./Laptop.svg";
import Loading from "../LoadingSpinner.gif";
import MarkerCompleted from "./Marker-completed.svg";
import MarkerCurrent from "./Marker-current.svg";
import MarkerNotStarted from "./Marker-notstarted.svg";
import Pending from "./Pending.svg";
import Phone from "./Phone.svg";
import Question_Filled from "./Question.svg";
import StepperLine from "./StepperLine.svg";
import SuccessSmallIllustration from "./Success-small-illustration.svg";
import Success from "./Success.svg";
import SuccessIllustration from "./SuccessIllustration.svg";
import ToggleSelected from "./Toggle-selected.svg";
import ToggleUnselected from "./Toggle-unselected.svg";
import Warning from "./Warning.svg";
import Attach from "./Attach.svg";
import BuildingAndDesktop_Filled from "./Building-Desktop-filled.svg";
import BuildingAndDesktop_Outlined from "./Building-Desktop-outlined.svg";
import Building_Filled from "./Building-filled.svg";
import Building_Outlined from "./Building-outlined.svg";
import Chat_Bubbles_Question from "./Chat-bubbles-question.svg";
import Desktop_Filled from "./Desktop-filled.svg";
import Desktop_Outlined from "./Desktop-outlined.svg";
import Error_LightGray from "./Error-lightgray.svg";
import Expired_Attention from "./Expired-attention.svg";
import External_Link from "./External-link.svg";
import InfoFilled_Attention from "./Info-filled-attention.svg";
import InfoOutlined_Attention from "./Info-outlined-attention.svg";
import Link from "./Link.svg";
import Notepad from "./Notepad-Edit.svg";
import Phone_Laptop from "./Phone-laptop.svg";
import Play from "./Play.svg";
import Question_Outlined from "./Question-outlined.svg";
import Refresh from "./Refresh.svg";
import Send from "./Send.svg";
import Star_Filled from "./Star-filled.svg";
import Star_Outlined from "./Star-outlined.svg";
import Subtract_Circle from "./Subtract-circle.svg";
import Support_Person from "./Support-person.svg";
import Ticket from "./Ticket.svg";

export const AddImage_dark: string = AddImage;
export const AvatarBlue_dark: string = AvatarBlueImage;
export const AvatarGreen_dark: string = AvatarGreenImage;
export const AvatarPink_dark: string = AvatarPinkImage;
export const AvatarPurple_dark: string = AvatarPurpleImage;
export const AvatarRed_dark: string = AvatarRedImage;
export const AvatarTeal_dark: string = AvatarTealImage;
export const CheckboxSelected_dark: string = CheckboxSelectedImage;
export const CheckboxUnselected_dark: string = CheckboxUnselectedImage;
export const ChevronDown_dark: string = ChevronDownIcon;
export const ChevronDownDisabled_dark: string = ChevronDownDisabledIcon;
export const ChevronLeft_dark: string = ChevronLeftIcon;
export const ChevronLeftDisabled_dark: string = ChevronLeftDisabledIcon;
export const ChevronRight_dark: string = ChevronRightIcon;
export const ChevronRightDisabled_dark: string = ChevronRightDisabledIcon;
export const ChevronUp_dark: string = ChevronUpIcon;
export const ChevronUpDisabled_dark: string = ChevronUpDisabledIcon;
export const ClearSearchBar_dark: string = ClearSearchBarIcon;
export const DismissIcon_dark: string = Dismiss;
export const EmptyIllustration_dark: string = EmptyIllustration;
export const EmptySmallIllustration_dark: string = EmptySmallIllustration;
export const ErrorIllustration_dark: string = ErrorIllustration;
export const ErrorSmallIllustration_dark: string = ErrorSmallIllustration;
export const ErrorIcon_dark: string = Error;
export const FileIcon_dark: string = FileIcon;
export const Image_dark: string = Image;
export const ExpiredIcon_dark: string = Expired;
export const ImportantIcon_dark: string = Important;
export const InfoFilled_dark: string = InfoFilled;
export const InfoOutline_dark: string = InfoOutline;
export const InReview_dark: string = InReview;
export const LaptopIcon_dark: string = Laptop;
export const LoadingIcon_dark: string = Loading;
export const MarkerCompleted_dark: string = MarkerCompleted;
export const MarkerCurrent_dark: string = MarkerCurrent;
export const MarkerNotStarted_dark: string = MarkerNotStarted;
export const PendingIcon_dark: string = Pending;
export const PhoneIcon_dark: string = Phone;
export const QuestionFilled_dark: string = Question_Filled;
export const StepperLine_dark: string = StepperLine;
export const SuccessSmallIllustration_dark: string = SuccessSmallIllustration;
export const SuccessIcon_dark: string = Success;
export const SuccessIllustration_dark: string = SuccessIllustration;
export const ToggleSelected_dark: string = ToggleSelected;
export const ToggleUnselected_dark: string = ToggleUnselected;
export const WarningIcon_dark: string = Warning;
export const Attach_dark: string = Attach;
export const BuildingAndDesktopFilled_dark: string = BuildingAndDesktop_Filled;
export const BuildingAndDesktopOutlined_dark: string = BuildingAndDesktop_Outlined;
export const BuildingFilled_dark: string = Building_Filled;
export const BuildingOutlined_dark: string = Building_Outlined;
export const ChatBubblesQuestion_dark: string = Chat_Bubbles_Question;
export const DesktopFilled_dark: string = Desktop_Filled;
export const DesktopOutlined_dark: string = Desktop_Outlined;
export const ErrorLightGray_dark: string = Error_LightGray;
export const ExpiredAttention_dark: string = Expired_Attention;
export const ExternalLink_dark: string = External_Link;
export const InfoFilledAttention_dark: string = InfoFilled_Attention;
export const InfoOutlinedAttention_dark: string = InfoOutlined_Attention;
export const Link_dark: string = Link;
export const Notepad_dark: string = Notepad;
export const PhoneLaptop_dark: string = Phone_Laptop;
export const Play_dark: string = Play;
export const QuestionOutlined_dark: string = Question_Outlined;
export const Refresh_dark: string = Refresh;
export const Send_dark: string = Send;
export const StarFilled_dark: string = Star_Filled;
export const StarOutlined_dark: string = Star_Outlined;
export const SubtractCircle_dark: string = Subtract_Circle;
export const SupportPerson_dark: string = Support_Person;
export const Ticket_dark: string = Ticket;
