import AvatarBlueImage from "./AvatarBlue.png";
import AvatarGreenImage from "./AvatarGreen.png";
import AvatarPinkImage from "./AvatarPink.png";
import AvatarPurpleImage from "./AvatarPurple.png";
import AvatarRedImage from "./AvatarRed.png";
import AvatarTealImage from "./AvatarTeal.png";
import Cancel from "./CancelIcon.svg";
import ChevronDownIcon from "./ChevronDown.svg";
import ChevronLeftIcon from "./ChevronLeftDefault.svg";
import ChevronLeftDisabledIcon from "./ChevronLeftDisabled.svg";
import ChevronRightIcon from "./ChevronRightDefault.svg";
import ChevronRightDisabledIcon from "./ChevronRightDisabled.png";
import Dismiss from "./DismissIcon.svg";
import Empty from "./Empty.png";
import EmptySection from "./EmptySection.png";
import Error from "./Error.png";
import ErrorBasic from "./BasicError.png";
import ErrorAlert from "./ErrorIcon.svg";
import ErrorSection from "./ErrorSection.png";
import File from "./FileIcon.png";
import HeaderLinePng from "./HeaderLine.png";
import ImageIconPng from "./ImageIcon.png";
import InfoAlert from "./InfoIcon.svg";
import LoadingGif from "./LoadingSpinner.gif";
import MyHubLogoLightIcon from "./MyHubLogo-Light.png";
import ProvidedIcon from "./Provided.svg";
import RadioEmptyIcon from "./RadioEmpty.png";
import RadioFilledIcon from "./RadioFilled.png";
import Success from "./Success.png";
import SuccessBasic from "./BasicSuccess.png";
import SuccessAlert from "./SuccessIcon.svg";
import SuccessSection from "./SuccessSection.png";
import TransparentHeaderLinePng from "./TransparentHeaderLine.png";
import VectorIcon from "./Vector.png";
import WarningAlert from "./WarningIcon.svg";

export const AvatarBlue: string = AvatarBlueImage;
export const AvatarGreen: string = AvatarGreenImage;
export const AvatarPink: string = AvatarPinkImage;
export const AvatarPurple: string = AvatarPurpleImage;
export const AvatarRed: string = AvatarRedImage;
export const AvatarTeal: string = AvatarTealImage;
export const CancelIcon: string = Cancel;
export const ChevronDown: string = ChevronDownIcon;
export const ChevronLeft: string = ChevronLeftIcon;
export const ChevronLeftDisabled: string = ChevronLeftDisabledIcon;
export const ChevronRight: string = ChevronRightIcon;
export const ChevronRightDisabled: string = ChevronRightDisabledIcon;
export const DismissIcon: string = Dismiss;
export const EmptyIcon: string = Empty;
export const EmptySectionIcon: string = EmptySection;
export const ErrorAlertIcon: string = ErrorAlert;
export const ErrorIcon: string = Error;
export const ErrorBasicIcon: string = ErrorBasic;
export const ErrorSectionIcon: string = ErrorSection;
export const FileIcon: string = File;
export const HeaderLine: string = HeaderLinePng;
export const ImageIcon: string = ImageIconPng;
export const InfoIcon: string = InfoAlert;
export const LoadingSpinner: string = LoadingGif;
export const MyHubIconLight: string = MyHubLogoLightIcon;
export const Provided: string = ProvidedIcon;
export const RadioEmpty: string = RadioEmptyIcon;
export const RadioFilled: string = RadioFilledIcon;
export const SuccessIcon: string = Success;
export const SuccessBasicIcon: string = SuccessBasic;
export const SuccessAlertIcon: string = SuccessAlert;
export const SuccessSectionIcon: string = SuccessSection;
export const TransparentHeaderLine: string = TransparentHeaderLinePng;
export const Vector: string = VectorIcon;
export const WarningIcon: string = WarningAlert;
