import AddImage from "./Add.svg";
import AvatarBlueImage from "./AvatarBlue.svg";
import AvatarGreenImage from "./AvatarGreen.svg";
import AvatarPinkImage from "./AvatarPink.svg";
import AvatarPurpleImage from "./AvatarPurple.svg";
import AvatarRedImage from "./AvatarRed.svg";
import AvatarTealImage from "./AvatarTeal.svg";
import CheckboxSelectedImage from "./Checkbox-selected.svg";
import CheckboxUnselectedImage from "./Checkbox-unselected.svg";
import ChevronDownIcon from "./Chevron-down.svg";
import ChevronDownDisabledIcon from "./ChevronDownDisabled.svg";
import ChevronLeftIcon from "./Chevron-left.svg";
import ChevronLeftDisabledIcon from "./ChevronLeftDisabled.svg";
import ChevronRightIcon from "./Chevron-right.svg";
import ChevronRightDisabledIcon from "./ChevronRightDisabled.svg";
import ChevronUpIcon from "./Chevron-up.svg";
import ChevronUpDisabledIcon from "./ChevronUpDisabled.svg";
import ClearSearchBarIcon from "./Clear-searchbar.svg";
import Dismiss from "./Dismiss.svg";
import EmptyIllustration from "./EmptyIllustration.svg";
import EmptySmallIllustration from "./EmptySmallIllustration.svg";
import ErrorIllustration from "./ErrorIllustration.svg";
import ErrorSmallIllustration from "./ErrorSmall-illustration.svg";
import Error from "./Error.svg";
import Expired from "./Expired.svg";
import FileIcon from "./FileIcon.svg";
import Image from "./Image.svg";
import Important from "./Important.svg";
import InfoFilled from "./Info-filled.svg";
import InfoOutline from "./Info-outline.svg";
import InReview from "./InReview.svg";
import Laptop from "./Laptop.svg";
import Loading from "../LoadingSpinner.gif";
import MarkerCompleted from "./Marker-completed.svg";
import MarkerCurrent from "./Marker-current.svg";
import MarkerNotStarted from "./Marker-notstarted.svg";
import MyHubLogo from "./MyHubLogo.svg";
import Pending from "./Pending.svg";
import Phone from "./Phone.svg";
import Question_Filled from "./Question.svg";
import StepperLine from "./StepperLine.svg";
import SuccessSmallIllustration from "./Success-small-illustration.svg";
import Success from "./Success.svg";
import SuccessIllustration from "./SuccessIllustration.svg";
import ToggleSelected from "./Toggle-selected.svg";
import ToggleUnselected from "./Toggle-unselected.svg";
import Warning from "./Warning.svg";
import Attach from "./Attach.svg";
import BuildingAndDesktop_Filled from "./Building-Desktop-filled.svg";
import BuildingAndDesktop_Outlined from "./Building-Desktop-outlined.svg";
import Building_Filled from "./Building-filled.svg";
import Building_Outlined from "./Building-outlined.svg";
import Chat_Bubbles_Question from "./Chat-bubbles-question.svg";
import Desktop_Filled from "./Desktop-filled.svg";
import Desktop_Outlined from "./Desktop-outlined.svg";
import Error_LightGray from "./Error-lightgray.svg";
import Expired_Attention from "./Expired-attention.svg";
import External_Link from "./External-link.svg";
import InfoFilled_Attention from "./Info-filled-attention.svg";
import InfoOutlined_Attention from "./Info-outlined-attention.svg";
import Link from "./Link.svg";
import Notepad from "./Notepad-Edit.svg";
import Phone_Laptop from "./Phone-laptop.svg";
import Play from "./Play.svg";
import Question_Outlined from "./Question-outlined.svg";
import Refresh from "./Refresh.svg";
import Send from "./Send.svg";
import Star_Filled from "./Star-filled.svg";
import Star_Outlined from "./Star-outlined.svg";
import Subtract_Circle from "./Subtract-circle.svg";
import Support_Person from "./Support-person.svg";
import Ticket from "./Ticket.svg";

export const AddImage_light: string = AddImage;
export const AvatarBlue_light: string = AvatarBlueImage;
export const AvatarGreen_light: string = AvatarGreenImage;
export const AvatarPink_light: string = AvatarPinkImage;
export const AvatarPurple_light: string = AvatarPurpleImage;
export const AvatarRed_light: string = AvatarRedImage;
export const AvatarTeal_light: string = AvatarTealImage;
export const CheckboxSelected_light: string = CheckboxSelectedImage;
export const CheckboxUnselected_light: string = CheckboxUnselectedImage;
export const ChevronDown_light: string = ChevronDownIcon;
export const ChevronDownDisabled_light: string = ChevronDownDisabledIcon;
export const ChevronLeft_light: string = ChevronLeftIcon;
export const ChevronLeftDisabled_light: string = ChevronLeftDisabledIcon;
export const ChevronRight_light: string = ChevronRightIcon;
export const ChevronRightDisabled_light: string = ChevronRightDisabledIcon;
export const ChevronUp_light: string = ChevronUpIcon;
export const ChevronUpDisabled_light: string = ChevronUpDisabledIcon;
export const ClearSearchBar_light: string = ClearSearchBarIcon;
export const DismissIcon_light: string = Dismiss;
export const EmptyIllustration_light: string = EmptyIllustration;
export const EmptySmallIllustration_light: string = EmptySmallIllustration;
export const ErrorIllustration_light: string = ErrorIllustration;
export const ErrorSmallIllustration_light: string = ErrorSmallIllustration;
export const ErrorIcon_light: string = Error;
export const FileIcon_light: string = FileIcon;
export const Image_light: string = Image;
export const ExpiredIcon_light: string = Expired;
export const ImportantIcon_light: string = Important;
export const InfoFilled_light: string = InfoFilled;
export const InfoOutline_light: string = InfoOutline;
export const InReview_light: string = InReview;
export const LaptopIcon_light: string = Laptop;
export const LoadingIcon_light: string = Loading;
export const MyHubLogo_light: string = MyHubLogo;
export const MarkerCompleted_light: string = MarkerCompleted;
export const MarkerCurrent_light: string = MarkerCurrent;
export const MarkerNotStarted_light: string = MarkerNotStarted;
export const PendingIcon_light: string = Pending;
export const PhoneIcon_light: string = Phone;
export const QuestionFilled_light: string = Question_Filled;
export const StepperLine_light: string = StepperLine;
export const SuccessSmallIllustration_light: string = SuccessSmallIllustration;
export const SuccessIcon_light: string = Success;
export const SuccessIllustration_light: string = SuccessIllustration;
export const ToggleSelected_light: string = ToggleSelected;
export const ToggleUnselected_light: string = ToggleUnselected;
export const WarningIcon_light: string = Warning;
export const Attach_light: string = Attach;
export const BuildingAndDesktopFilled_light: string = BuildingAndDesktop_Filled;
export const BuildingAndDesktopOutlined_light: string = BuildingAndDesktop_Outlined;
export const BuildingFilled_light: string = Building_Filled;
export const BuildingOutlined_light: string = Building_Outlined;
export const ChatBubblesQuestion_light: string = Chat_Bubbles_Question;
export const DesktopFilled_light: string = Desktop_Filled;
export const DesktopOutlined_light: string = Desktop_Outlined;
export const ErrorLightGray_light: string = Error_LightGray;
export const ExpiredAttention_light: string = Expired_Attention;
export const ExternalLink_light: string = External_Link;
export const InfoFilledAttention_light: string = InfoFilled_Attention;
export const InfoOutlinedAttention_light: string = InfoOutlined_Attention;
export const Link_light: string = Link;
export const Notepad_light: string = Notepad;
export const PhoneLaptop_light: string = Phone_Laptop;
export const Play_light: string = Play;
export const QuestionOutlined_light: string = Question_Outlined;
export const Refresh_light: string = Refresh;
export const Send_light: string = Send;
export const StarFilled_light: string = Star_Filled;
export const StarOutlined_light: string = Star_Outlined;
export const SubtractCircle_light: string = Subtract_Circle;
export const SupportPerson_light: string = Support_Person;
export const Ticket_light: string = Ticket;
