name: Build and Deploy SPFx Library

on:
  pull_request:
    branches: "*"
  workflow_dispatch: # Add this event to enable manual triggering

permissions:
  pull-requests: write
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Build and Test
        run: npm run build
