name: Build SPFx Library

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add this event to enable manual triggering

permissions:
  pull-requests: write
  contents: write

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies for ux-components
        run: cd ux-components && npm install

      - name: Verify change files
        run: cd ux-components && npm run check-change

      - name: Build and Test for ux-components
        run: cd ux-components && npm run build

      - name: Install dependencies for dashboard
        run: cd dashboard && npm install

      - name: Build dashboard
        run: cd dashboard && npm run build
