name: Release

# only on manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    # You'd need to create this environment and add the secrets NPM_AUTHTOKEN and REPO_PAT
    environment: release

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Don't save creds in the git config (so it's easier to override later)
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm run build

      - name: Publish package
        run: |
          npm run release -- -y -n $NPM_AUTHTOKEN
        env:
          NPM_AUTHTOKEN: ${{ secrets.NPM_AUTHTOKEN }}
